parameters:
#    site_site.example.class: Site\SiteBundle\Example

services:
#    site_site.example:
#        class: %site_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
